---
title: Safe Streets Halton
timezone: Pacific/Pago_Pago
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header_pages:
- "/campaigns/not-five-minutes"
- "/get-involved"
- "/news"
- "/about"
- "/contact-us"
announcement:
  show: false
  icon: "\U0001F4E2"
  text: The province is restricting bike lanes in Halton Region
  link: "/get-involved"
  action: Learn More
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
description: Safe Streets Halton is a grass-roots organization on a mission to eliminate
  all traffic-related deaths and serious injuries in Halton, Ontario.
baseurl: 
url: 
permalink: "/:categories/:title"
twitter_username: HaltonStreets
facebook_username: HaltonStreets
instagram_username: SafeStreetsHalton
tiktok_username: SafeStreetsHalton
email: info@safestreetshalton.ca
whitelist:
- jekyll-redirect-from
