---
title: Safe Streets Halton
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  volunteer-postings:
    title: Volunteer Postings
    output: true
  ontario-election-2025:
    title: Ontario Election 2025
    output: true
    permalink: /elections/ontario-2025/:name
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: post
- scope:
    path: ''
    type: volunteer-postings
  values:
    layout: volunteer-posting
- scope:
    path: ''
  values:
    image: "/assets/Social_Avatar_512x512.png"
- scope:
    path: ''
    type: ontario-election-2025
  values:
    layout: election-survey
header_pages:
- "/get-involved"
- "/news"
- "/about"
- "/contact-us"
announcement:
  show: false
  icon: "\U0001F4E2"
  danger_level: danger
  text: The Government of Ontario is restricting how we make our streets safe in Halton
    Region
  link: "/campaigns/we-want-safer-streets-ontario"
  action: Learn More
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
description: Safe Streets Halton is a grass-roots organization on a mission to eliminate
  all traffic-related deaths and serious injuries in Halton, Ontario.
baseurl: 
url: 
permalink: "/:categories/:title"
twitter_username: HaltonStreets
facebook_username: HaltonStreets
instagram_username: SafeStreetsHalton
tiktok_username: SafeStreetsHalton
email: info@safestreetshalton.ca
whitelist:
- jekyll-redirect-from
csv_reader:
    converters:
      - all
    headers: true
    encoding: utf-8