---
title: Safe Streets Halton
timezone: EST
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header_pages:
- "/campaigns/not-five-minutes"
- "/get-involved"
- "/news"
- "/about"
- "/contact-us"
announcement:
  show: false
  icon: "\U0001F4E2"
  text: Join our Annual General Meeting on May 30th!
  link: "/get-involved"
  action: Learn More
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
permalink: "/:categories/:title"
twitter_username: HaltonStreets
facebook_username: HaltonStreets
instagram_username: SafeStreetsHalton
tiktok_username: SafeStreetsHalton
whitelist:
- jekyll-redirect-from
