---
title: Safe Streets Halton
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  ontario-election-2025:
    title: Ontario Election 2025
    output: true
    permalink: "/elections/ontario-2025/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  volunteer:
    title: Volunteer Postings
    output: true
    permalink: get-involved
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: post
- scope:
    path: ''
    type: volunteer-postings
  values:
    layout: volunteer-posting
- scope:
    path: ''
  values:
    image: "/assets/Social_Avatar_512x512.png"
- scope:
    path: ''
    type: ontario-election-2025
  values:
    layout: election-survey
header_pages:
- "/get-involved"
- "/news"
- "/about"
- "/contact-us"
announcement:
  show: false
  icon: "\U0001F5F3️"
  danger_level: none
  text: We asked candidates where they stand on transportation & safety. Read their
    responses.
  link: "/elections/ontario-2025"
  action: Learn More
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
description: Safe Streets Halton is a grass-roots organization on a mission to eliminate
  all traffic-related deaths and serious injuries in Halton, Ontario.
baseurl: 
url: 
permalink: "/:categories/:title"
twitter_username: HaltonStreets
facebook_username: HaltonStreets
instagram_username: SafeStreetsHalton
tiktok_username: SafeStreetsHalton
email: info@safestreetshalton.ca
whitelist:
- jekyll-redirect-from
csv_reader:
  converters:
  - all
  headers: true
  encoding: utf-8
